package com.example.demo.controller;

import com.example.demo.model.User;
import com.example.demo.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * This class controls flow to and from the database using GET and POST calls. The backend listens
 * on port 8080 and uses calls to query and modify the database.
 *
 * DEVELOPERS: To access the database and run the backend, you must first open a ssh tunnel with the terminal
 * command below. This terminal will be a different one than you run the backend in:
 *
 * ssh -L localhost:3306:localhost:3306 [CS_USERNAME]@cs506x14.cs.wisc.edu
 */
@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {

    @Autowired // This means to get the bean called userRepository
        // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    /**
     * Adds a new User to the MySQL Database with a unique ID, a username, and a password
     *
     * @param username the user-decided username
     * @param password the user-decided password
     * @return a "saved" string if the user was successfully added to the Database
     */
    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String username
            , @RequestParam String password) {
        // @ResponseBody means the returned String is the response, now a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User user = new User();
        user.setUsername(username);
        user.setPassword(password);
        userRepository.save(user);
        return "Saved";
    }

    /**
     * Finds and returns an iterable of all users and user information stored in the MySQL Database
     *
     * @return an Iterable of all users in the database
     */
    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    /**
     * Finds and returns a specific user in the MySQL Database by their unique username
     *
     * @param username the username of the given user
     * @return the user entity if it exists, or null if there does not exist a user with the given username
     */
    @GetMapping(path="/user")
    public @ResponseBody User getUserByUsername(@RequestParam String username) {
        return userRepository.findByUsername(username);
    }
}