package com.example.demo.model;

import jakarta.persistence.*;

/**
 * Entity class representing a March Madness Team.
 *
 * This class is mapped to a database table "march_maddness_teams". It contains
 * an autogenerated ID, team's name, their seed as well as the region.
 */

@Entity
@Table(name = "march_madness_teams")
public class MarchMadnessTeam {

     /** Unique identifier for the team (auto-generated). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Name of the team. */
    @Column(name = "team_name", nullable = false)
    private String name;

    /** Seed number of the team in the tournament. */
    @Column(name = "seed", nullable = false)
    private int seed;

    /** Region in which the team is placed. */
    @Column(name = "region", nullable = false)
    private String region;

    @Column(name = "winsPerRound")
    private String winsPerRound;

    /*
     * Default required constructor.
     */
    public MarchMadnessTeam() {}

    /**
     * Constructor for an individual March Madness Team
     * 
     * @param name Name of the team
     * @param seed Seed number of the team
     * @param region Region the team is placed in
     */
    public MarchMadnessTeam(String name, int seed, String region) {
        this.name = name;
        this.seed = seed;
        this.region = region;
    }

    /**
     * Gets the id of the team
     * 
     * @return The unique identifier of the team
     */
    public Long getId() { return id; }

    /**
     * Gets the name of the team
     * 
     * @return The name of the team
     */
    public String getName() { return name; }

    /**
     * Sets the name of the team
     */
    public void setName(String name) { this.name = name; }

    /**
     * Gets the seed number of the team
     * 
     * @return The seed number
     */
    public int getSeed() { return seed; }

    /**
     * Sets the seed number of the team
     */
    public void setSeed(int seed) { this.seed = seed; }

    /**
     * Gets the region in which the team was placed
     * 
     * @return The region
     */
    public String getRegion() { return region; }

    /**
     * Sets the region for the team
     */
    public void setRegion(String region) { this.region = region; }

    /**
     * Gets the bit-wise string depicting wins per round for the team
     * 
     * @return Bit-wise string
     */
    public String getWinsPerRound() {  return winsPerRound;  }
    
    /**
     * Sets the wins per round for the team
     */
    public void setWinsPerRound(String winsPerRound) {  this.winsPerRound = winsPerRound;  }
}
