package com.example.demo.model;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * Entity representing a message.
 *
 * <p>This class is mapped to a database table using {@link Entity}. It contains
 * an autogenerated ID and a content field to store message text.</p>
 */
@Entity
public class Message {

    /**
     * Generates the unique identifier for the message.
     * */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String content; // String content of message

    /**
     * Default constructor for Spring Data JPA, an abstraction layer over Java Persistence API,
     * which simplifies database operations and makes it easier to for Java applications
     * to interact with databases.
     */
    public Message() {
    }

    /**
     * Constructs a new {@code Message} with the specified content.
     *
     * @param content The message content.
     */
    public Message(String content) {
        this.content = content;
    }

    /**
     * Returns the unique ID of the message.
     *
     * @return The message ID.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique ID of the message.
     *
     * @param id The message ID.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the message content.
     *
     * @return The message content.
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the message content.
     *
     * @param content The new message content.
     */
    public void setContent(String content) {
        this.content = content;
    }
}